---
- name: Install Starship (git-aware prompt)
  hosts: all 

  tasks:

  - name: Download Starship install script
    ansible.builtin.get_url:
      url: https://starship.rs/install.sh
      dest: /tmp/install_starship.sh
      mode: 0755
    become: true

  - name: Run install_starship.sh
    ansible.builtin.command: /tmp/install_starship.sh -y
    become: true

  - name: Add starship to bashrc
    ansible.builtin.lineinfile:
      path: ~/.bashrc
      line: eval "$(starship init bash)"
      state: present
      create: yes
    become_user: "{{ user }}"
    become: true

  - name: Copy custom starship.toml
    ansible.builtin.copy:
      src: ../deploy_files/starship.toml
      dest: /home/{{ user }}/.config/starship.toml
    become: true