- name: Configure Ubuntu keyboard & locale
  hosts: all

  tasks:
  - name: Set timezone to Europe/Copenhagen
    community.general.timezone:
      name: Europe/Copenhagen
    become: True

  # Roles available via ansible.galaxy_role_file in Vagrantfile
  roles:
    # Configure keyboard
    - role: gantsign.keyboard
      keyboard_model: pc105
      keyboard_layout: dk

    # Configure locale
    - role: oefenweb.locales
      locales_present:
        - en_DK.UTF-8
        - en_US.UTF-8
      locales_default:
        lang: en_DK.UTF-8
      become: true